# Generated by Django 5.2.6 on 2025-10-08 05:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'House',
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.CreateModel(
            name='House_Cup_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('season', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'House Cup Year',
                'verbose_name_plural': 'House Cup Years',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('activity_type', models.CharField(choices=[('sports', 'Sports'), ('esport', 'Esports'), ('academics', 'Academics'), ('arts', 'Arts'), ('other', 'Other')], max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('points_distribution', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'DRAFT'), ('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house_cup_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaderboard.house_cup_year')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_earned', models.IntegerField(null=True)),
                ('placement', models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score', to='leaderboard.activity')),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='score', to='leaderboard.house')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score',
                'verbose_name_plural': 'Scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['activity', 'house'], name='leaderboard_activit_446b1d_idx'), models.Index(fields=['created_at'], name='leaderboard_created_8a81ad_idx')],
                'unique_together': {('activity', 'house')},
            },
        ),
    ]
