# Generated by Django 5.2.6 on 2025-10-11 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_participation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='leaderboard_activit_446b1d_idx',
        ),
        migrations.RemoveIndex(
            model_name='score',
            name='leaderboard_created_8a81ad_idx',
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='score',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='score_type',
            field=models.CharField(choices=[('placement', 'Placement'), ('participation', 'Participation'), ('bonus', 'Bonus'), ('penalty', 'Penalty')], default='placement', max_length=20),
        ),
        migrations.AlterField(
            model_name='score',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leaderboard.activity'),
        ),
        migrations.AlterField(
            model_name='score',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leaderboard.house'),
        ),
        migrations.AlterField(
            model_name='score',
            name='placement',
            field=models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='points_earned',
            field=models.IntegerField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.RemoveField(
            model_name='score',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='score',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='verified_by',
        ),
    ]
