# Generated by Django 5.2.6 on 2025-10-11 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0003_alter_score_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
