# Generated by Django 5.2.6 on 2025-10-11 02:28

from django.db import migrations

from django.db import migrations

def populate_points_distribution(apps, schema_editor):
    Activity = apps.get_model('leaderboard', 'Activity')
    
    for activity in Activity.objects.all():
        if not activity.points_distribution:
            activity.points_distribution = {
                1: activity.max_points,
                2: int(activity.max_points * 0.8),
                3: int(activity.max_points * 0.6),
                4: int(activity.max_points * 0.4),
                5: int(activity.max_points * 0.2)
            }
            activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_score_updated_at'),
    ]

    operations = [
        migrations.RunPython(populate_points_distribution),
    ]
