# Generated by Django 5.2.6 on 2025-10-11 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_auto_20251011_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='score_type',
        ),
    ]
