# Generated by Django 5.2.6 on 2025-10-11 03:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0007_remove_score_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-created_at'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AddField(
            model_name='score',
            name='participation_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='leaderboard.participation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='score',
            name='placement',
            field=models.IntegerField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th')], help_text='Select the placement (1st, 2nd, 3rd, etc.)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
