# Generated by Django 5.2.6 on 2025-10-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0008_alter_score_options_score_participation_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='participation_id',
            new_name='participation',
        ),
    ]
